In [34]:
import pandas as pd

In [45]:
df_2024 = pd.read_csv('../files/processed/datatran_merged_base_2007_2024.csv', encoding='latin1', sep=';')

In [47]:
df_2024.head()

,ï»¿id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,tracado_via,uso_solo,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,175827.0,2007-01-01,Segunda,17:30:00,MG,381.0,485.0,BETIM,Falta de atenÃ§Ã£o,ColisÃ£o traseira,...,Cruzamento,Urbano,2,0,0,0,2,0,0,2
1,174220.0,2007-01-01,Segunda,14:15:00,RJ,40.0,43.9,AREAL,Velocidade incompatÃ­vel,SaÃ­da de Pista,...,Curva,Rural,1,0,0,0,1,0,0,1
2,175540.0,2007-01-01,Segunda,16:00:00,PE,101.0,32.0,IGARASSU,NÃ£o guardar distÃ¢ncia de seguranÃ§a,ColisÃ£o lateral,...,Reta,Rural,2,0,0,0,2,0,0,2
3,175544.0,2007-01-01,Segunda,12:00:00,MG,50.0,0.2,ARAGUARI,Outras,SaÃ­da de Pista,...,Curva,Rural,4,0,3,1,0,0,4,1
4,175545.0,2007-01-01,Segunda,08:40:00,MG,381.0,397.4,NOVA UNIAO,Outras,SaÃ­da de Pista,...,Curva,Rural,1,0,0,0,1,0,0,1

Verificando colunas de todos os datasets

In [42]:
def analise_colunas(ano_inicio, ano_fim):
  colunas_por_ano = {}

  for ano in range(ano_inicio,ano_fim+1):
    path = f'C:/Users/joseb/OneDrive/Documentos/GitHub/RoadSafeAI/files/processed/datatran_merged_base_2007_2024.csv'
            
    df = pd.read_csv(path, encoding='latin1', sep=";", nrows=0)
    colunas_por_ano[ano] = set(df.columns)
    print(f"{ano}: {len(df.columns)} colunas")
    
  if(colunas_por_ano):
    ano_ref = min(colunas_por_ano.keys())
    coluna_ref = colunas_por_ano[ano_ref]
    
    print(f"\nComparando com o ano de referência ({ano_ref}):")
    
    for ano, colunas in colunas_por_ano.items():
      if ano != ano_ref:
        novas_colunas = colunas - coluna_ref
        colunas_faltantes = coluna_ref - colunas
        
        if novas_colunas or colunas_faltantes:
          print(f"\nDiferenças encontradas no ano {ano}:")
          if novas_colunas:
              print(f"Novas colunas: {novas_colunas}")
          if colunas_faltantes:
              print(f"Colunas ausentes: {colunas_faltantes}")
        else:
          print(f"\nAno {ano}: Mesmas colunas que {ano_ref}")

In [43]:
analise_colunas(2007,2024)

2007: 25 colunas
2008: 25 colunas
2009: 25 colunas
2010: 25 colunas
2011: 25 colunas
2012: 25 colunas
2013: 25 colunas
2014: 25 colunas
2015: 25 colunas
2016: 25 colunas
2017: 25 colunas
2018: 25 colunas
2019: 25 colunas
2020: 25 colunas
2021: 25 colunas
2022: 25 colunas
2023: 25 colunas
2024: 25 colunas

Comparando com o ano de referência (2007):

Ano 2008: Mesmas colunas que 2007

Ano 2009: Mesmas colunas que 2007

Ano 2010: Mesmas colunas que 2007

Ano 2011: Mesmas colunas que 2007

Ano 2012: Mesmas colunas que 2007

Ano 2013: Mesmas colunas que 2007

Ano 2014: Mesmas colunas que 2007

Ano 2015: Mesmas colunas que 2007

Ano 2016: Mesmas colunas que 2007

Ano 2017: Mesmas colunas que 2007

Ano 2018: Mesmas colunas que 2007

Ano 2019: Mesmas colunas que 2007

Ano 2020: Mesmas colunas que 2007

Ano 2021: Mesmas colunas que 2007

Ano 2022: Mesmas colunas que 2007

Ano 2023: Mesmas colunas que 2007

Ano 2024: Mesmas colunas que 2007

É possivel notar uma alteração nas colunas entre os anos 2015, 2016 e 2017

In [44]:
analise_colunas(2015,2017)

2015: 25 colunas
2016: 25 colunas
2017: 25 colunas

Comparando com o ano de referência (2015):

Ano 2016: Mesmas colunas que 2015

Ano 2017: Mesmas colunas que 2015

No ano de 2016, a coluna ano não foi declarada.

A partir do ano de 2017, as colunas referentes a região do acidente, como latitude e longitude começaram a ser registradas.

É possivel diante dessas diferenças, criar dois datasets, um com as 26 colunas que existem de 2007 a 2024 (adicionando a coluna ano no dataset de 2016) e criar uma coluna com dados referente a região, com os dataset de 2017 a 2024.